### ISSUE TITLE
Where can I find supplementary materials for your paper?

### ISSUE THREAD

**Issue by zpc-666** [bokveizen/Feedback-Gradient-Descent#2]
Hello, thank you for this great work, we are interested in your work. "For the specific settings for each sub-experiment, refer to the supplementary material for the details not mentioned in the main text.", so where can I find supplementary materials for your paper?

**Comment by bokveizen** [comment]
Thank you for being interested in our work! Sorry for missing the supplementary materials. Let me upload the file to this repo.

**Comment by zpc-666** [comment]
Thank you !
